services:
  typesense:
    image: typesense/typesense:28.0
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=test123
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    command: "--data-dir /data --api-key=test123 --enable-cors"
    restart: "no"
volumes:
  typesense_data:
